#spring.application.name=JournalApp

#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=journaldbs


#spring.data.mongodb.uri=mongodb+srv://gautamchy2002_db_user:a6h2YNeyc1djEfbk@cluster0.iqk7im8.mongodb.net/journaldbs?retryWrites=true&w=majority
#spring.data.mongodb.auto-index-creation=true

#humare case me user id ki jrurart nhi hai agar hogi to iss tarah likhi jayegi
#spring.data.mongodb.username=myjournaluser
#spring.data.mongodb.password=mypassword
