
spring:
#  redis:
#

#    for local
#    host: localhost
#    port: 6379
  data:
    redis:
      url: redis://default:DrIftwsuxDLOLbIXwZSPXdbIRWgThqSe@produce-prairie-communicative-71228.db.redis.io:15575

    mongodb:
      uri: mongodb+srv://gautamchy2002_db_user:a6h2YNeyc1djEfbk@cluster0.iqk7im8.mongodb.net/journaldbs?retryWrites=true&w=majority
      database: journaldbs
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: gautamchy2002@gmail.com
    password: plxv tcjq suph rpxd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081
  servlet:
    context-path: /journal

weather:
  api:
    key : e694537cd65feaba19fba44250a3900d


